Complete rewrite

diff --git a/karbs b/karbs
--- a/karbs
+++ b/karbs
@@ -1,66 +1,289 @@
 #!/bin/sh
-# Kristofers Auto Rice Boostrapping Script (KARBS)
+# Kristofer's Auto Rice Bootstrapping Script (KARBS)
 # by Kristofers Solo
 # License: GNU GPLv3
 
-echo "Choose display server (X11 / Wayland)[1/2]: "
-read -r USER_INPUT
+### OPTIONS AND VARIABLES ###
 
+while getopts ":a:r:b:p:h" o; do case "${o}" in
+	h) printf "Optional arguments for custom use:\\n  -r: Dotfiles repository (local file or url)\\n  -p: Dependencies and programs csv (local file or url)\\n  -a: AUR helper (must have pacman-like syntax)\\n  -h: Show this message\\n" && exit 1 ;;
+	r) dotfilesrepo=${OPTARG} && git ls-remote "$dotfilesrepo" || exit 1 ;;
+	b) repobranch=${OPTARG} ;;
+	p) progsfile=${OPTARG} ;;
+	a) aurhelper=${OPTARG} ;;
+	*) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
+	esac done
 
-# Get display server type from user
-if [ "$USER_INPUT" = 1 ]; then
-    DISPLAY_SERVER="X11"
-elif [ "$USER_INPUT" = 2 ]; then
-    DISPLAY_SERVER="wayland"
-else
-    echo "Wrong input. Please try again."
-    exit
-fi
+[ -z "$dotfilesrepo" ] && dotfilesrepo="https://github.com/kristoferssolo/solorice.git"
+# [ -z "$progsfile" ] && progsfile="https://raw.githubusercontent.com//LARBS/master/progs.csv"
+[ -z "$progsfile" ] && progsfile="https://github.com/kristoferssolo/karbs/blob/main/pkg-files/X11-pkgs.csv"
+[ -z "$aurhelper" ] && aurhelper="paru"
+[ -z "$repobranch" ] && repobranch="master"
 
+### FUNCTIONS ###
 
-# Install paru
-if pacman -Q paru; then
-    :
-else
-    sudo pacman -S --noconfirm rust-src git wget fakeroot
-    git clone https://aur.archlinux.org/paru-bin
-    cd paru-bin || exit
-    makepkg -si
-    cd ..
-    rm -rf paru-bin
-fi
+installpkg() { pacman --noconfirm --needed -S "$1" >/dev/null 2>&1; }
 
-FILE="pkg-files/$DISPLAY_SERVER-pkgs"
+error() {
+	printf "%s\n" "$1" >&2
+	exit 1
+}
 
-if [ -f "$FILE" ]; then
-    paru -Syu --noconfirm --needed - < $FILE
-else
-    curl -LO https://raw.githubusercontent.com/kristoferssolo/karbs/main/$FILE
-    paru -Syu --noconfirm --needed - < $DISPLAY_SERVER-pkgs
-    rm -f $DISPLAY_SERVER-pkgs
-fi
+welcomemsg() {
+	dialog --title "Welcome!" --msgbox "Welcome to Kristofer's Auto-Rice Bootstrapping Script!\\n\\nThis script will automatically install a fully-featured Linux desktop, which I use as my main machine.\\n\\n-Kristofers" 10 60
 
-git clone https://github.com/kristoferssolo/solorice "$HOME/solorice"
-cp -raf "$HOME"/solorice/{./config,./local,.zshenv} "$HOME"
-git clone https://github.com/kristoferssolo/SoloVim "$HOME"/.config/nvim
-rm -rf "$HOME"/solorice
-mkdir -p "$HOME"/{Downloads,Documents,Videos,Music,Pictures/screenshots}
+	dialog --colors --title "Important Note!" --yes-label "All ready!" --no-label "Return..." --yesno "Be sure the computer you are using has current pacman updates and refreshed Arch keyrings.\\n\\nIf it does not, the installation of some programs might fail." 8 70
+}
 
-if [ $DISPLAY_SERVER = "wayland" ]; then
-    rm -rf "$HOME"/.config/{awesome,picom,sx,zsh/.zprofile-X11}
-    mv "$HOME"/.config/zsh/.zprofile-wayland "$HOME"/.config/zsh/.zprofile
-    chsh -s /bin/zsh
-    zsh
-    Hyprland
-else
-    rm -rf "$HOME"/.config/{hypr,waybar,zsh/.zprofile-wayland}
-    mv "$HOME"/.config/zsh/.zprofile-X11 "$HOME"/.config/zsh/.zprofile
-    git clone https://github.com/streetturtle/awesome-wm-widgets "$HOME"/.config/awesome/awesome-wm-widgets
-    chsh -s /bin/zsh
-    zsh
-    echo -e "\n\n\033[1;31mFor weather widget to work, enter API-key from https://openweathermap.org, latitude and longitude in '~/.config/awesome/weather' file, each on seperate line.\033[0m"
-    echo "API-key"
-    echo "latitude"
-    echo "longitude"
-    echo -e "\nEverything else is ready to go. You can run 'sx' or reboot."
-fi
+getuserandpass() {
+	# Prompts user for new username an password.
+	name=$(dialog --inputbox "First, please enter a name for the user account." 10 60 3>&1 1>&2 2>&3 3>&1) || exit 1
+	while ! echo "$name" | grep -q "^[a-z_][a-z0-9_-]*$"; do
+		name=$(dialog --no-cancel --inputbox "Username not valid. Give a username beginning with a letter, with only lowercase letters, - or _." 10 60 3>&1 1>&2 2>&3 3>&1)
+	done
+	pass1=$(dialog --no-cancel --passwordbox "Enter a password for that user." 10 60 3>&1 1>&2 2>&3 3>&1)
+	pass2=$(dialog --no-cancel --passwordbox "Retype password." 10 60 3>&1 1>&2 2>&3 3>&1)
+	while ! [ "$pass1" = "$pass2" ]; do
+		unset pass2
+		pass1=$(dialog --no-cancel --passwordbox "Passwords do not match.\\n\\nEnter password again." 10 60 3>&1 1>&2 2>&3 3>&1)
+		pass2=$(dialog --no-cancel --passwordbox "Retype password." 10 60 3>&1 1>&2 2>&3 3>&1)
+	done
+}
+
+usercheck() {
+	! { id -u "$name" >/dev/null 2>&1; } ||
+		dialog --colors --title "WARNING!" --yes-label "CONTINUE" --no-label "No wait..." --yesno "The user \`$name\` already exists on this system. KARBS can install for a user already existing, but it will \\Zboverwrite\\Zn any conflicting settings/dotfiles on the user account.\\n\\nKARBS will \\Zbnot\\Zn overwrite your user files, documents, videos, etc., so don't worry about that, but only click <CONTINUE> if you don't mind your settings being overwritten.\\n\\nNote also that KARBS will change $name's password to the one you just gave." 14 70
+}
+
+preinstallmsg() {
+	dialog --title "Let's get this party started!" --yes-label "Let's go!" --no-label "No, nevermind!" --yesno "The rest of the installation will now be totally automated, so you can sit back and relax.\\n\\nIt will take some time, but when done, you can relax even more with your complete system.\\n\\nNow just press <Let's go!> and the system will begin installation!" 13 60 || {
+		clear
+		exit 1
+	}
+}
+
+adduserandpass() {
+	# Adds user `$name` with password $pass1.
+	dialog --infobox "Adding user \"$name\"..." 4 50
+	useradd -m -g wheel -s /bin/zsh "$name" >/dev/null 2>&1 ||
+		usermod -aG wheel "$name"
+	export repodir="/home/$name/.local/src"
+	mkdir -p "$repodir"
+	chown -R "$name":wheel "$(dirname "$repodir")"
+	echo "$name:$pass1" | chpasswd
+	unset pass1 pass2
+}
+
+refreshkeys() {
+	case "$(readlink -f /sbin/init)" in
+	*systemd*)
+		dialog --infobox "Refreshing Arch Keyring..." 4 40
+
+		grep -q "^\[multilib\]" /etc/pacman.conf ||
+			echo "[multilib]
+            Include = /etc/pacman.d/mirrorlist" >>/etc/pacman.conf
+
+		pacman --noconfirm -S archlinux-keyring >/dev/null 2>&1
+		;;
+	*)
+		dialog --infobox "Enabling Arch Repositories..." 4 40
+		pacman --noconfirm --needed -S artix-keyring artix-archlinux-support >/dev/null 2>&1
+
+		grep -q "^\[lib32\]" /etc/pacman.conf ||
+			echo "[lib32]
+            Include = /etc/pacman.d/mirrorlist" >>/etc/pacman.conf
+
+		grep -q "^\[universe\]" /etc/pacman.conf ||
+			echo "[universe]
+            Server = https://universe.artixlinux.org/\$arch" >>/etc/pacman.conf
+
+		for repo in extra community multilib; do
+			grep -q "^\[$repo\]" /etc/pacman.conf ||
+				echo "[$repo]
+                Include = /etc/pacman.d/mirrorlist-arch" >>/etc/pacman.conf
+		done
+		pacman -Sy >/dev/null 2>&1
+		pacman-key --populate archlinux >/dev/null 2>&1
+		;;
+	esac
+}
+
+newperms() { # Set special doas settings for install (or after).
+	echo "$" >>/etc/doas.conf
+}
+
+manualinstall() { # Installs $1 manually. Used only for AUR helper here.
+	# Should be run after repodir is created and var is set.
+	dialog --infobox "Installing \"$1\", an AUR helper..." 4 50
+	doas -u "$name" mkdir -p "$repodir/$1"
+	doas -u "$name" git clone --depth 1 "https://aur.archlinux.org/$1.git" "$repodir/$1" >/dev/null 2>&1 ||
+		{
+			cd "$repodir/$1" || return 1
+			doas -u "$name" git pull --force origin master
+		}
+	cd "$repodir/$1" || exit
+	doas -u "$name" -D "$repodir/$1" makepkg --noconfirm -si >/dev/null 2>&1 || return 1
+}
+
+maininstall() { # Installs all needed programs from main repo.
+	dialog --title "KARBS Installation" --infobox "Installing \`$1\` ($n of $total). $1 $2" 5 70
+	installpkg "$1"
+}
+
+gitmakeinstall() {
+	progname="$(basename "$1" .git)"
+	dir="$repodir/$progname"
+	dialog --title "KARBS Installation" --infobox "Installing \`$progname\` ($n of $total) via \`git\` and \`make\`. $(basename "$1") $2" 5 70
+	doas -u "$name" git clone --depth 1 "$1" "$dir" >/dev/null 2>&1 || {
+		cd "$dir" || return 1
+		doas -u "$name" git pull --force origin master
+	}
+	cd "$dir" || exit 1
+	make >/dev/null 2>&1
+	make install >/dev/null 2>&1
+	cd /tmp || return 1
+}
+
+aurinstall() {
+	dialog --title "KARBS Installation" --infobox "Installing \`$1\` ($n of $total) from the AUR. $1 $2" 5 70
+	echo "$aurinstalled" | grep -q "^$1$" && return 1
+	doas -u "$name" "$aurhelper" -S --noconfirm "$1" >/dev/null 2>&1
+}
+
+pipinstall() {
+	dialog --title "KARBS Installation" --infobox "Installing the Python package \`$1\` ($n of $total). $1 $2" 5 70
+	[ -x "$(command -v "pip")" ] || installpkg python-pip >/dev/null 2>&1
+	yes | pip install "$1"
+}
+
+installationloop() {
+	([ -f "$progsfile" ] && cp "$progsfile" /tmp/progs.csv) || curl -Ls "$progsfile" | sed '/^#/d' >/tmp/progs.csv
+	total=$(wc -l </tmp/progs.csv)
+	aurinstalled=$(pacman -Qqm)
+	while IFS=, read -r tag program comment; do
+		n=$((n + 1))
+		echo "$comment" | grep -q "^\".*\"$" && comment="$(echo "$comment" | sed -E "s/(^\"|\"$)//g")"
+		case "$tag" in
+		"A") aurinstall "$program" "$comment" ;;
+		"G") gitmakeinstall "$program" "$comment" ;;
+		"P") pipinstall "$program" "$comment" ;;
+		*) maininstall "$program" "$comment" ;;
+		esac
+	done </tmp/progs.csv
+}
+
+putgitrepo() { # Downloads a gitrepo $1 and places the files in $2 only overwriting conflicts
+	dialog --infobox "Downloading and installing config files..." 4 60
+	[ -z "$3" ] && branch="master" || branch="$repobranch"
+	dir=$(mktemp -d)
+	[ ! -d "$2" ] && mkdir -p "$2"
+	chown "$name":wheel "$dir" "$2"
+	doas -u "$name" git clone --recursive -b "$branch" --depth 1 --recurse-submodules "$1" "$dir" >/dev/null 2>&1
+	doas -u "$name" cp -rfT "$dir" "$2"
+}
+
+systembeepoff() {
+	dialog --infobox "Getting rid of that retarded error beep sound..." 10 50
+	rmmod pcspkr
+	echo "blacklist pcspkr" >/etc/modprobe.d/nobeep.conf
+}
+
+finalize() {
+	dialog --infobox "Preparing welcome message..." 4 50
+	dialog --title "All done!" --msgbox "Congrats! Provided there were no hidden errors, the script completed successfully and all the programs and configuration files should be in place.\\n\\nTo run the new graphical environment, log out and log back in as your new user, then run the command \"startx\" to start the graphical environment (it will start automatically in tty1).\\n\\n.t Luke" 12 80
+}
+
+### THE ACTUAL SCRIPT ###
+
+### This is how everything happens in an intuitive format and order.
+
+# Check if user is root on Arch distro. Install dialog.
+pacman --noconfirm --needed -Sy dialog || error "Are you sure you're running this as the root user, are on an Arch-based distribution and have an internet connection?"
+
+# Welcome user and pick dotfiles.
+welcomemsg || error "User exited."
+
+# Get and verify username and password.
+getuserandpass || error "User exited."
+
+# Give warning if user already exists.
+usercheck || error "User exited."
+
+# Last chance for user to back out before install.
+preinstallmsg || error "User exited."
+
+### The rest of the script requires no user input.
+
+# Refresh Arch keyrings.
+refreshkeys || error "Error automatically refreshing Arch keyring. Consider doing so manually."
+
+for x in curl ca-certificates base-devel git ntp zsh; do
+	dialog --title "KARBS Installation" --infobox "Installing \`$x\` which is required to install and configure other programs." 5 70
+	installpkg "$x"
+done
+
+dialog --title "KARBS Installation" --infobox "Synchronizing system time to ensure successful and secure installation of software..." 4 70
+ntpdate 0.us.pool.ntp.org >/dev/null 2>&1
+
+adduserandpass || error "Error adding username and/or password."
+
+# Allow user to run doas without password. Since AUR programs must be installed
+# in a fakeroot environment, this is required for all builds with AUR.
+newperms "permit nopass :wheel"
+
+# Make pacman colorful, concurrent downloads and Pacman eye-candy.
+grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
+sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.conf
+
+# Use all cores for compilation.
+sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf
+
+manualinstall "$aurhelper" || error "Failed to install AUR helper."
+
+# The command that does all the installing. Reads the progs.csv file and
+# installs each needed program the way required. Be sure to run this only after
+# the user has been created and has privileges to run doas without a password
+# and all build dependencies are installed.
+installationloop
+
+dialog --title "KARBS Installation" --infobox "Finally, installing \`libxft-bgra\` to enable color emoji in suckless software without crashes." 5 70
+yes | doas -u "$name" "$aurhelper" -S libxft-bgra-git >/dev/null 2>&1
+
+# Install the dotfiles in the user's home directory
+putgitrepo "$dotfilesrepo" "/home/$name" "$repobranch"
+rm -f "/home/$name/README.md" "/home/$name/LICENSE"
+# make git ignore deleted LICENSE & README.md files
+git update-index --assume-unchanged "/home/$name/README.md" "/home/$name/LICENSE"
+
+# Most important command! Get rid of the beep!
+systembeepoff
+
+# Make zsh the default shell for the user.
+chsh -s /bin/zsh "$name" >/dev/null 2>&1
+doas -u "$name" mkdir -p "/home/$name/.cache/zsh/"
+doas -u "$name" mkdir -p "/home/$name/.config/abook/"
+doas -u "$name" mkdir -p "/home/$name/.config/mpd/playlists/"
+
+# dbus UUID must be generated for Artix runit.
+dbus-uuidgen >/var/lib/dbus/machine-id
+
+# Use system notifications for Brave on Artix
+echo "export \$(dbus-launch)" >/etc/profile.d/dbus.sh
+
+# Tap to click
+[ ! -f /etc/X11/xorg.conf.d/40-libinput.conf ] && printf 'Section "InputClass"
+		Identifier "libinput touchpad catchall"
+		MatchIsTouchpad "on"
+		MatchDevicePath "/dev/input/event*"
+		Driver "libinput"
+	# Enable left mouse button by tapping
+	Option "Tapping" "on"
+EndSection' >/etc/X11/xorg.conf.d/40-libinput.conf
+
+# Fix fluidsynth/pulseaudio issue.
+grep -q "OTHER_OPTS='-a pulseaudio -m alsa_seq -r 48000'" /etc/conf.d/fluidsynth ||
+	echo "OTHER_OPTS='-a pulseaudio -m alsa_seq -r 48000'" >>/etc/conf.d/fluidsynth
+
+# Last message! Install complete!
+finalize
+clear
